variables:
  configuration: 'Release'

pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

steps:
- task: UseDotNet@2
  inputs:
    version: 3.1.302
  displayName: 'Use .Net Core sdk 3.1.302'

- script: dotnet tool restore
  displayName: Restore dotnet tools

- script: dotnet cake --bootstrap --verbosity=$(verbosity)
  displayName: Bootstrap cake

- script: dotnet cake --configuration="$(configuration)" --outputDir="$(Build.ArtifactStagingDirectory)"