variables:
  shoudlPushNuget: false
  configuration: 'Release'

pool:
  name: Hosted Windows 2019 with VS2019

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

steps:
- task: PowerShell@2
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: '--outputDir=$(Build.ArtifactStagingDirectory) --configuration=$(configuration)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), variables['shouldPushNuget'])
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'ViewPagerIndicator NuGet v3'
