variables:
  configuration: 'Release'

pool:
  name: Hosted Windows 2019 with VS2019

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

steps:
- task: PowerShell@2
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: '--outputDir=$(Build.ArtifactStagingDirectory) --configuration=$(configuration)'